packages/quark-icons/rollup.config.js, packages/quark/rollup.config.js
=> build: add optimazam options

packages/quark/src/cell/doc-react.en-US.md, packages/quark/src/cell/doc-react.zh-CN.md
=> docs(cell): fix spelling error

CONTRIBUTING.md, CONTRIBUTING.zh-CN.md, README.md, README.zh-CN.md
**这个 PR 做了什么?** (简要描述所做更改)
添加贡献说明英文版
**这个 PR 是什么类型?** (至少选择一个)
=> feat: add developer contributions in english

packages/quark/src/badge/doc-react.en-US.md, packages/quark/src/badge/doc-react.zh-CN.md, packages/quark/src/field/doc-react.en-US.md, packages/quark/src/field/doc-react.zh-CN.md, packages/quark/src/field/doc.en-US.md, packages/quark/src/field/doc.zh-CN.md
- fix badge&field  spelling error
- Bandge => Badge
- text-olor -> text-color
- Methed -> Method
=> Fix spelling error

packages/quark-reactify/src/index.ts
Merge regular can improve reactify update performance
test code
`let arr = [];
for (var i = 0; i < 100000; i++) {
if (i % 2 === 0) {
arr.push("onClick");
} else {
arr.push("onclick");
}
}
function test1(prop) {
if (prop.match(/^on[A-Z]/)) {
return prop[2].toLowerCase() + prop.substr(3);
}
if (prop.match(/^on[a-z]/)) {
return prop[2] + prop.substr(3);
}
}
function test2(prop) {
if (prop.match(/^on[A-Za-z]/)) {
return prop[2].toLowerCase() + prop.substr(3);
}
}
console.time('1')
arr.forEach(prop=>{
test1(prop)
})
console.timeEnd('1')
// 10.195ms
console.time('2')
arr.forEach(prop=>{
test2(prop)
})
console.timeEnd('2')`
// 7.537ms
=> feat: improve reactify performance

packages/quark/src/cascadepicker/index.tsx
* simplify cascadepicker `changePickerData` function logic
=> refactor: simplify cascadepicker function logic

packages/quark/src/badge/doc-react.en-US.md, packages/quark/src/badge/doc-react.zh-CN.md, packages/quark/src/badge/doc.en-US.md, packages/quark/src/badge/doc.zh-CN.md
=> docs: async docs && demo

packages/quark/src/button/index.tsx
fix button prop  icon like  string "www_http" instead of 
"https://m.hellobike.com/resource/helloyun/16682/Agnve_tel%20(1).png"
fix Event ts warning
=> fix(Button): fix button icon url

packages/quark/src/button/doc-react.zh-CN.md, packages/quark/src/datetimepicker/DatePicker.tsx, packages/quark/src/imagepreview/doc-react.en-US.md, packages/quark/src/imagepreview/doc-react.zh-CN.md, packages/quark/src/list/doc.en-US.md, packages/quark/src/list/doc.zh-CN.md, packages/quark/src/marquee/doc-react.en-US.md, packages/quark/src/marquee/doc-react.zh-CN.md, packages/quark/src/navbar/doc.en-US.md, packages/quark/src/navbar/doc.zh-CN.md, packages/quark/src/noticebar/doc.zh-CN.md, packages/quark/src/popupextra/index.tsx, packages/quark/src/popupextra/style.css, packages/quark/src/search/index.tsx, packages/quark/src/search/style.css, packages/quark/src/swipe/index.tsx, packages/quark/src/tag/doc-react.en-US.md, packages/quark/src/tag/doc-react.zh-CN.md
1. ```tsx 和 ```html 颜色有点不太一样的，看文档几乎都是html确实也更好看，这边统一一下
2.  事例中缺少hook const [open2, setOpen2] = useState(false);
3.  ts type.: any -> TouchEvent
4.  search 组件按钮的交互 & close 鼠标移入 transition
other：缩进
=> docs: format doc & TouchEvent type

demo.html, packages/quark/src/button/doc-react.en-US.md, packages/quark/src/button/doc-react.zh-CN.md, packages/quark/src/button/style.css, packages/quark/src/cascadepicker/doc-react.en-US.md, packages/quark/src/cascadepicker/doc-react.zh-CN.md, packages/quark/src/datetimepicker/doc-react.en-US.md, packages/quark/src/datetimepicker/doc-react.zh-CN.md, packages/quark/src/dialog/doc-react.en-US.md, packages/quark/src/dialog/doc-react.zh-CN.md, packages/quark/src/marketdialog/doc-react.zh-CN.md, packages/quark/src/overlay/doc-react.en-US.md, packages/quark/src/overlay/doc-react.zh-CN.md, packages/quark/src/picker/doc-react.en-US.md, packages/quark/src/picker/doc-react.zh-CN.md, packages/quark/src/popover/doc-react.en-US.md, packages/quark/src/popover/doc-react.zh-CN.md, packages/quark/src/popupextra/doc-react.en-US.md, packages/quark/src/popupextra/doc-react.zh-CN.md, packages/quark/src/progress/doc-react.en-US.md, packages/quark/src/progress/doc-react.zh-CN.md, packages/quark/src/textarea/doc-react.en-US.md, packages/quark/src/textarea/doc-react.zh-CN.md, packages/quark/src/tooltip/doc-react.en-US.md, packages/quark/src/tooltip/doc-react.zh-CN.md
1. 文档禁用过于强硬了，暂时还是不要吧 
2. 并且只禁用文档的话，不能解决外部引用组件的问题
3. button 层级的位置不对导致 user-select: none; 失效
4. 看了一下 Textarea / Button/ Progress react组件文档有错误
5. 顺带优化了一些示例
=> fix: issue#134

example/src/README.md
=> fix: lint example md tree

example/src/config.json, packages/quark/src/field/style.css, packages/quark/src/popup/doc-react.en-US.md, packages/quark/src/popup/doc-react.zh-CN.md
1. 增加一点间距会更加美观，原来紧挨着不太好看
2. 这边其实不太需要用到 position 定位
3. fix component name(一处文档目录，还有就是Popup的引用)
=> fix(Field): increase spacing & remove useless

packages/quark/src/rate/index.tsx
=> feat(rate): del invalid code

packages/quark/src/loading/style.css
修复loading在其他组件内不居中的问题
可以查看图片loading组件
=> fix(Loading): fix loading center

packages/quark/src/image/index.tsx
=> feat(image): simplified code

packages/quark/src/navbar/index.tsx, packages/quark/src/navbar/style.css
1. 这边也有点击选中文字的bug
2. 点击太生硬了，毕竟是按钮的功能应该加点active效果
=> fix(navbar): Increase click interaction&fix select

packages/quark/src/imagepreview/index.tsx
API调用方式内部使用isFn来判断是否打开，我理解调用默认就是打开的，那么这个open参数就是无效的了
=> feat(ImagePreview): delete invalid param open

packages/quark/src/imagepreview/index.tsx
=> feat(ImagePreview): change any to TouchEvent

packages/quark/src/list/demo.vue
add List demo property sticky
优化使用demo的体验
=> docs(List): add List demo property sticky

packages/quark/src/imagepreview/index.tsx
delete ineffective code
fix index ts type
=> feat(ImagePreview): delete ineffective code

CONTRIBUTING.md, CONTRIBUTING.zh-CN.md
=> feat(MD): sync tree

packages/quark/src/button/demo.vue
=> docs: update button/demo.vue

packages/quark/src/list/demo.vue
=> docs(List): fix demo height

packages/quark/src/tabbar/index.tsx
=> feat:(Tabbar): optimize code

packages/quark/src/dialog/demo.vue, packages/quark/src/dialog/doc-react.en-US.md, packages/quark/src/dialog/doc-react.zh-CN.md, packages/quark/src/dialog/doc.en-US.md, packages/quark/src/dialog/doc.zh-CN.md
=> docs(Dialog): async demo and docs

packages/quark/src/loading/doc-react.en-US.md, packages/quark/src/loading/doc-react.zh-CN.md, packages/quark/src/loading/doc.en-US.md, packages/quark/src/loading/doc.zh-CN.md, packages/quark/src/loading/index.tsx
=> feat(Loading): add fontSize vm&vh unit

example/src/config.json, packages/quark/src/virtuallist/demo.vue, packages/quark/src/virtuallist/doc-react.en-US.md, packages/quark/src/virtuallist/doc-react.zh-CN.md, packages/quark/src/virtuallist/doc.en-US.md, packages/quark/src/virtuallist/doc.zh-CN.md, packages/quark/src/virtuallist/index.tsx, packages/quark/src/virtuallist/style.css
=> feat(VirtualList): VirtualList init

packages/quark/src/rate/demo.vue, packages/quark/src/rate/doc-react.en-US.md, packages/quark/src/rate/doc-react.zh-CN.md, packages/quark/src/rate/doc.en-US.md, packages/quark/src/rate/doc.zh-CN.md, packages/quark/src/rate/index.tsx
Rate组件支持传入图片icon
弃用icon变量，使用imgicon为了更贴合图片icon属性，
icon变量保留为以后支持传入其他icon做准备
=> feat(Rate): support image icon

packages/quark/package.json
`npm` 添加 `global-css.js` 文件, 方便二次开发;
=> chore: add export global-css.js

example/src/sites/doc/components/Header.vue
=> fix: optimize isHomePage

.vscode/settings.json, example/src/config.json, example/src/sites/doc/router.ts, packages/quark-react/src/watermark/index.ts, packages/quarkd/src/index.ts, packages/quarkd/src/watermark/demo.scss, packages/quarkd/src/watermark/demo.vue, packages/quarkd/src/watermark/doc-react.en-US.md, packages/quarkd/src/watermark/doc-react.zh-CN.md, packages/quarkd/src/watermark/doc.en-US.md, packages/quarkd/src/watermark/doc.zh-CN.md, packages/quarkd/src/watermark/index.test.js, packages/quarkd/src/watermark/index.tsx, packages/quarkd/src/watermark/style.css
add a new component  —— Watermark
It can help users add text or patterns on the page (suitable for preventing information theft scenarios)
=> feat(index): add watermark component

.github/workflows/deploy2io.yml, .github/workflows/reademe-contributors.yml, .github/workflows/sync-docs-to-React-website.yml, .github/workflows/sync-docs-to-Vue-website.yml, .github/workflows/sync-gitee.yml
Let forked repositories skip CI runs
=> chore: ci improve

example/src/sites/mobile-vue/App.vue
=> Fix: h5 demo display
